# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171119_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(choices=[('S', '学生'), ('T', '老师')], default='S', max_length=1, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relation',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
