# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20171122_1533'),
        ('users', '0003_auto_20171122_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsProfile', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relation',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='关系'),
        ),
    ]
