# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171122_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='relation',
            new_name='relations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goods',
        ),
    ]
