# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
