# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsprofile_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsprofile',
            name='img',
            field=models.ImageField(upload_to='goods/images/', verbose_name='展示图'),
        ),
    ]
