# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20171119_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsprofile',
            name='img',
            field=models.ImageField(upload_to='media/goods/goods_profile/images', verbose_name='展示图'),
        ),
    ]
