# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20171119_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_profiles', to='goods.Category', verbose_name='类别'),
        ),
    ]
