# Generated by Django 2.0.1 on 2018-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_learn', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
