# Generated by Django 2.0.1 on 2018-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_learn', '0005_goodsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='media/goods_images/', verbose_name='轮播图'),
        ),
    ]
