# Generated by Django 2.0.1 on 2018-01-30 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_learn', '0010_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='配送地址')),
                ('status', models.CharField(choices=[('w', '待支付'), ('r', '已支付')], default='w', max_length=1, verbose_name='支付状态')),
                ('order_mount', models.FloatField(verbose_name='订单金额')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-add_time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='shoppingitem',
            unique_together={('user', 'goods')},
        ),
    ]
