# Generated by Django 2.0.1 on 2018-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_learn', '0013_order_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_mount',
            field=models.FloatField(default=0, verbose_name='订单金额'),
        ),
    ]
