# Generated by Django 2.0.1 on 2018-02-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_learn', '0015_auto_20180201_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
